// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Board Customizer → Wheels*
 */
export interface CustomizerDocumentDataWheelsItem {
  /**
   * Texture field in *Board Customizer → Wheels*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.wheels[].texture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  texture: prismic.ImageField<never>;

  /**
   * UID field in *Board Customizer → Wheels*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.wheels[].uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;
}

/**
 * Item in *Board Customizer → Decks*
 */
export interface CustomizerDocumentDataDecksItem {
  /**
   * Texture field in *Board Customizer → Decks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.decks[].texture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  texture: prismic.ImageField<never>;

  /**
   * UID field in *Board Customizer → Decks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.decks[].uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;
}

/**
 * Item in *Board Customizer → Metals*
 */
export interface CustomizerDocumentDataMetalsItem {
  /**
   * UID field in *Board Customizer → Metals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.metals[].uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Color field in *Board Customizer → Metals*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.metals[].color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;
}

/**
 * Content for Board Customizer documents
 */
interface CustomizerDocumentData {
  /**
   * Wheels field in *Board Customizer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.wheels[]
   * - **Tab**: Wheels
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  wheels: prismic.GroupField<Simplify<CustomizerDocumentDataWheelsItem>> /**
   * Decks field in *Board Customizer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.decks[]
   * - **Tab**: Deck
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  decks: prismic.GroupField<Simplify<CustomizerDocumentDataDecksItem>> /**
   * Metals field in *Board Customizer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: customizer.metals[]
   * - **Tab**: Metal
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  metals: prismic.GroupField<Simplify<CustomizerDocumentDataMetalsItem>>;
}

/**
 * Board Customizer document from Prismic
 *
 * - **API ID**: `customizer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CustomizerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CustomizerDocumentData>,
    "customizer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | TeamSlice
  | VideoSlice
  | SlidesSlice
  | ProductsSectionSlice
  | HeroSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Product Card documents
 */
interface ProductCardDocumentData {
  /**
   * name field in *Product Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Price field in *Product Card*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Image field in *Product Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Customizer Link field in *Product Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.customizer_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  customizer_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Category field in *Product Card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: moody
   * - **API ID Path**: product_card.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    "moody" | "bb4l" | "miss-board" | "alpha",
    "filled"
  >;
}

/**
 * Product Card document from Prismic
 *
 * - **API ID**: `product_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductCardDocumentData>,
    "product_card",
    Lang
  >;

/**
 * Content for Skater Card documents
 */
interface SkaterCardDocumentData {
  /**
   * Name field in *Skater Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skater_card.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Fg Image field in *Skater Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skater_card.fg_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fg_image: prismic.ImageField<never>;

  /**
   * Bg Image field in *Skater Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skater_card.bg_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;

  /**
   * Customizer Link field in *Skater Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: skater_card.customizer_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  customizer_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Team field in *Skater Card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skater_card.team
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  team: prismic.SelectField<"alpha" | "bb4l" | "miss-board" | "moody">;
}

/**
 * Skater Card document from Prismic
 *
 * - **API ID**: `skater_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkaterCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SkaterCardDocumentData>,
    "skater_card",
    Lang
  >;

export type AllDocumentTypes =
  | CustomizerDocument
  | HomepageDocument
  | ProductCardDocument
  | SkaterCardDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Skateboard Deck field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.skateboard_deck
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  skateboard_deck: prismic.ImageField<never>;

  /**
   * Skateboard Wheel field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.skateboard_wheel_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  skateboard_wheel_image: prismic.ImageField<never>;

  /**
   * Bolts Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bolts_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  bolts_color: prismic.ColorField;

  /**
   * Truck Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.truck_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  truck_color: prismic.ColorField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *ProductsSection → Default → Primary → Product*
 */
export interface ProductsSectionSliceDefaultPrimaryProductItem {
  /**
   * Product Card field in *ProductsSection → Default → Primary → Product*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: products_section.default.primary.product[].product_card
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product_card: prismic.ContentRelationshipField<"product_card">;
}

/**
 * Primary content in *ProductsSection → Default → Primary*
 */
export interface ProductsSectionSliceDefaultPrimary {
  /**
   * Heading field in *ProductsSection → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: products_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *ProductsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Product field in *ProductsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: products_section.default.primary.product[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  product: prismic.GroupField<
    Simplify<ProductsSectionSliceDefaultPrimaryProductItem>
  >;
}

/**
 * Default variation for ProductsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductsSection*
 */
type ProductsSectionSliceVariation = ProductsSectionSliceDefault;

/**
 * ProductsSection Shared Slice
 *
 * - **API ID**: `products_section`
 * - **Description**: ProductsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSectionSlice = prismic.SharedSlice<
  "products_section",
  ProductsSectionSliceVariation
>;

/**
 * Primary content in *Slides → Default → Primary*
 */
export interface SlidesSliceDefaultPrimary {
  /**
   * Theme field in *Slides → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"Blue" | "Orange" | "Navy" | "Lime">;

  /**
   * FG Image field in *Slides → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.default.primary.fg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fg_image: prismic.ImageField<never>;

  /**
   * BG Image field in *Slides → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.default.primary.bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;

  /**
   * Heading field in *Slides → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Slides → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Slides → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Slides Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SlidesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Slides → Image first → Primary*
 */
export interface SlidesSliceImageFirstPrimary {
  /**
   * Theme field in *Slides → Image first → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.imageFirst.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"Blue" | "Orange" | "Navy" | "Lime">;

  /**
   * FG Image field in *Slides → Image first → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.imageFirst.primary.fg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fg_image: prismic.ImageField<never>;

  /**
   * BG Image field in *Slides → Image first → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.imageFirst.primary.bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;

  /**
   * Heading field in *Slides → Image first → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.imageFirst.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Slides → Image first → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.imageFirst.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Slides → Image first → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: slides.imageFirst.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Image first variation for Slides Slice
 *
 * - **API ID**: `imageFirst`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidesSliceImageFirst = prismic.SharedSliceVariation<
  "imageFirst",
  Simplify<SlidesSliceImageFirstPrimary>,
  never
>;

/**
 * Slice variation for *Slides*
 */
type SlidesSliceVariation = SlidesSliceDefault | SlidesSliceImageFirst;

/**
 * Slides Shared Slice
 *
 * - **API ID**: `slides`
 * - **Description**: Slides
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidesSlice = prismic.SharedSlice<"slides", SlidesSliceVariation>;

/**
 * Item in *Team → Default → Primary → Skaters*
 */
export interface TeamSliceDefaultPrimarySkatersItem {
  /**
   * Skater field in *Team → Default → Primary → Skaters*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.skaters[].skater
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  skater: prismic.ContentRelationshipField<"skater_card">;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Heading field in *Team → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Skaters field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.skaters[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skaters: prismic.GroupField<Simplify<TeamSliceDefaultPrimarySkatersItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * YouTube ID field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.youtube_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube_id: prismic.KeyTextField;

  /**
   * Placeholder Image field in *Video → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.placeholder_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  placeholder_image: prismic.ImageField<never>;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CustomizerDocument,
      CustomizerDocumentData,
      CustomizerDocumentDataWheelsItem,
      CustomizerDocumentDataDecksItem,
      CustomizerDocumentDataMetalsItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ProductCardDocument,
      ProductCardDocumentData,
      SkaterCardDocument,
      SkaterCardDocumentData,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProductsSectionSlice,
      ProductsSectionSliceDefaultPrimaryProductItem,
      ProductsSectionSliceDefaultPrimary,
      ProductsSectionSliceVariation,
      ProductsSectionSliceDefault,
      SlidesSlice,
      SlidesSliceDefaultPrimary,
      SlidesSliceImageFirstPrimary,
      SlidesSliceVariation,
      SlidesSliceDefault,
      SlidesSliceImageFirst,
      TeamSlice,
      TeamSliceDefaultPrimarySkatersItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
