import type { Metadata } from "next";
import { DM_Mono, Bowlby_One_SC } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import { SVGFilters } from "@/components/SVGFilter";

const dmMono = DM_Mono({
  subsets: ["latin"],
  variable: "--font-dm-mono",
  weight: "500",
  display: "swap",
});

const bowlby = Bowlby_One_SC({
  variable: "--font-bowlby-one",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bowlby.variable} ${dmMono.variable} font-mono font-medium text-zinc-800 antialiased`}
      >
        <Header />
        <main>{children}</main>
        <SVGFilters />
      </body>
    </html>
  );
}
