// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  products_section: dynamic(() => import("./ProductsSection")),
  slides: dynamic(() => import("./Slides")),
  team: dynamic(() => import("./Team")),
  video: dynamic(() => import("./Video")),
};
